<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExcelDataReader" Version="3.8.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
		<PackageReference Include="ClosedXML" Version="0.102.2" />
	</ItemGroup>

	<!-- ЯВНАЯ ссылка на сборку System.Speech -->
	<ItemGroup>
		<Reference Include="System.Speech" />
	</ItemGroup>
</Project>
